import type {
  RadioChangeEvent,
  CheckboxChangeEvent,
  TabKey,
  InputRef,
  SelectValue,
  TreeSelectValue,
  ColorMode,
  TableColumnSettingProps,
  MessageApi,
  NoticeApi,
  ModalApi,
  ModalInstance,
  GridBreakpoint,
  GridResponsive,
  SkeletonAvatarConfig,
  WatermarkFont,
  ImagePreviewApi,
  OptionSelectEvent,
} from "react-kui";

export type PublicTypeRegressions = [
  RadioChangeEvent,
  CheckboxChangeEvent,
  TabKey,
  InputRef,
  SelectValue,
  TreeSelectValue,
  ColorMode,
  TableColumnSettingProps,
  MessageApi,
  NoticeApi,
  ModalApi,
  ModalInstance,
  GridBreakpoint,
  GridResponsive<number>,
  SkeletonAvatarConfig,
  WatermarkFont,
  ImagePreviewApi,
  OptionSelectEvent,
];
